# 开发环境配置文件
# 通过 --spring.profiles.active=dev 激活

spring:
  datasource:
    # 开发环境使用H2内存数据库（便于快速开发）
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;NON_KEYWORDS=VALUE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: update  # 开发环境自动创建/更新表结构
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect  # H2数据库方言
        format_sql: true
    open-in-view: false  # 避免懒加载问题
  
  # H2数据库控制台配置（仅开发环境）
  h2:
    console:
      enabled: true
      path: /h2-console

  # 关闭基于 H2 的初始化与控制台，保持与生产一致
  sql:
    init:
      mode: never

# 开发环境日志配置
logging:
  level:
    root: INFO
    com.bj.wms: DEBUG
    org.springframework.web: DEBUG
