# Spring Boot 应用配置文件
# 使用YAML格式，比properties文件更易读和结构化

# 服务器配置
server:
  port: 8080  # 应用端口
  servlet:
    context-path: /api/v1  # API路径前缀

# Spring配置
spring:
  # 应用基本信息
  application:
    name: wms-backend
  
  # 数据源配置 - 由具体环境配置文件定义
  # 开发环境：application-dev.yml (H2)
  # 生产环境：application-prod.yml (MySQL)
  
  # JPA/Hibernate配置 - 由具体环境配置文件定义
  # 开发环境：application-dev.yml
  # 生产环境：application-prod.yml
  
  # H2数据库控制台配置 - 由开发环境配置文件定义
  
  # 安全配置：删除默认用户，使用自定义 SecurityConfig 放行策略

  # 国际化消息编码（用于校验消息、异常消息等）
  messages:
    encoding: UTF-8

# 日志配置
logging:
  level:
    com.bj.wms: DEBUG  # 项目包日志级别
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  # 设置日志输出编码，避免控制台中文乱码
  charset:
    console: UTF-8
    file: UTF-8

# 自定义配置
wms:
  jwt:
    secret: mySecretKey123456789012345678901234567890  # JWT密钥（生产环境应使用环境变量）
    expiration: 86400000  # Token过期时间（24小时，单位：毫秒）
  
  # 分页配置
  page:
    default-size: 10
    max-size: 100
