# 生产环境配置文件
# 通过 --spring.profiles.active=prod 激活

spring:
  datasource:
    url: jdbc:mysql://8.137.116.128:3306/wms_db?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false&maxReconnects=3
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: wms
    password: Wms!Passw0rd
    
    # HikariCP 连接池配置（生产环境优化）
    hikari:
      # 连接池基本配置
      minimum-idle: 5                    # 最小空闲连接数
      maximum-pool-size: 20              # 最大连接池大小
      idle-timeout: 300000               # 空闲连接超时时间（5分钟）
      max-lifetime: 1800000              # 连接最大生命周期（30分钟）
      connection-timeout: 30000          # 连接超时时间（30秒）
      
      # MySQL 特定配置
      connection-test-query: SELECT 1    # 连接测试查询
      validation-timeout: 5000           # 验证超时时间（5秒）
      
      # 连接泄漏检测
      leak-detection-threshold: 60000    # 连接泄漏检测阈值（60秒）
      
      # 连接池名称
      pool-name: WMS-Prod-HikariCP
  
  jpa:
    hibernate:
      ddl-auto: validate  # 生产环境只验证表结构，不自动修改
    show-sql: false  # 生产环境不显示SQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false

# 生产环境日志配置
logging:
  level:
    root: WARN
    com.bj.wms: INFO
    # HikariCP 连接池日志（生产环境保持INFO级别）
    com.zaxxer.hikari: INFO
    com.zaxxer.hikari.HikariConfig: INFO
    com.zaxxer.hikari.pool.HikariPool: INFO
  file:
    name: logs/wms-backend.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  # 设置日志输出编码，避免控制台中文乱码
  charset:
    console: UTF-8
    file: UTF-8

# 生产环境JWT配置（使用环境变量）
wms:
  jwt:
    secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
    expiration: ${JWT_EXPIRATION:86400000}
