# 开发环境配置文件
# 通过 --spring.profiles.active=dev 激活

spring:
  datasource:
    url: jdbc:mysql://8.137.116.128:3306/wms_db?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: wms
    password: Wms!Passw0rd

  jpa:
    hibernate:
      ddl-auto: validate  # 开发环境与生产一致：仅校验，不改表
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  # 关闭基于 H2 的初始化与控制台，保持与生产一致
  sql:
    init:
      mode: never

# 开发环境日志配置
logging:
  level:
    root: INFO
    com.bj.wms: DEBUG
    org.springframework.web: DEBUG
